name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  call_reusable_workflow:
    uses: aassalax/workflows/.github/workflows/build-kt.yml@main
