name: Project Card Moved Listener

on:
  issues:
    types: [ opened, edited, labeled, unlabeled ]

jobs:
  log_project_card_move:
    runs-on: ubuntu-latest

    steps:
      - name: Display issue info
        run: |
          echo "Issue event detected: ${{ github.event.action }}"
          
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Title: ${{ github.event.issue.title }}"
          echo "Description: ${{ github.event.issue.body }}"
          echo "State: ${{ github.event.issue.state }}"
          
          echo "Labels:"
          for label in ${{ toJson(github.event.issue.labels) }}; do echo "$label"; done
    
