name: Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  call_reusable_workflow:
    uses: aassalax/workflows/.github/workflows/release-kt.yml@main