name: Publish Release

on:
  push:
    tags:
      - 'stable'
      - 'release'

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  call_reusable_workflow:
    uses: aassalax/workflows/.github/workflows/release-kt.yml@main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}