name: Version Bump

on:
  push:
    tags:
      - stable

permissions:
  contents: write
  pull-requests: read

jobs:
  call_reusable_workflow:
    uses: aassalax/workflows/.github/workflows/version-bump.yml@main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}